services:
  db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vinyl
    ports:
      - '5433:5432' # 5433 côté host pour éviter les conflits locaux
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '3000:3000'
    restart: always
    environment:
      # Ces variables peuvent être surchargées par le .env
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: vinyl

volumes:
  db_data: 